//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLCN.SpeechCognizeConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationTestEntities : DbContext
    {
        public ApplicationTestEntities()
            : base("name=ApplicationTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KLCN_Tab_SpeechRecognition> KLCN_Tab_SpeechRecognition { get; set; }
        public virtual DbSet<KLCN_Tab_SpeechCalculate> KLCN_Tab_SpeechCalculate { get; set; }
    }
}
