//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLCN.SpeechCognizeConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLCN_Tab_SpeechRecognition
    {
        public int ID { get; set; }
        public string Subject { get; set; }
        public string AttachmentURI { get; set; }
        public string AttachmentContentType { get; set; }
        public string MsgId { get; set; }
        public string UserobjectId { get; set; }
        public string PhysicsURI { get; set; }
        public string Email { get; set; }
        public string Account { get; set; }
        public string CurrentDirectory { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Content { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
